#############################################################################
# Makefile for building: untitled13
# Generated by qmake (3.1) (Qt 5.9.9)
# Project:  untitled13.pro
# Template: app
# Command: J:\QT\5.9.9\msvc2017_64\bin\qmake.exe -o Makefile untitled13.pro -spec win32-msvc
#############################################################################

MAKEFILE      = Makefile

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = J:\QT\5.9.9\msvc2017_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = J:\QT\5.9.9\msvc2017_64\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = J:\QT\5.9.9\msvc2017_64\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: untitled13.pro J:\QT\5.9.9\msvc2017_64\mkspecs\win32-msvc\qmake.conf J:\QT\5.9.9\msvc2017_64\mkspecs\features\spec_pre.prf \
		J:\QT\5.9.9\msvc2017_64\mkspecs\common\angle.conf \
		J:\QT\5.9.9\msvc2017_64\mkspecs\common\msvc-desktop.conf \
		J:\QT\5.9.9\msvc2017_64\mkspecs\qconfig.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_3danimation.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_3danimation_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_3dcore.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_3dcore_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_3dextras.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_3dextras_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_3dinput.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_3dinput_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_3dlogic.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_3dlogic_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_3dquick.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_3dquick_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_3dquickanimation.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_3dquickanimation_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_3dquickextras.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_3dquickextras_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_3dquickinput.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_3dquickrender.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_3dquickscene2d.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_3dquickscene2d_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_3drender.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_3drender_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_accessibility_support_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_axbase.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_axbase_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_axcontainer.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_axcontainer_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_axserver.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_axserver_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_bluetooth.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_bluetooth_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_bootstrap_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_concurrent.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_concurrent_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_core.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_core_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_dbus.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_dbus_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_designer.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_designer_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_designercomponents_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_egl_support_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_fb_support_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_fontdatabase_support_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_gamepad.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_gamepad_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_gui.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_gui_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_help.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_help_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_location.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_location_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_multimedia.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_multimedia_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_multimediawidgets.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_network.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_network_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_networkauth.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_networkauth_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_nfc.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_nfc_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_opengl.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_opengl_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_openglextensions.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_openglextensions_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_platformcompositor_support_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_positioning.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_positioning_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_printsupport.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_printsupport_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_qml.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_qml_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_qmldebug_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_qmltest.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_qmltest_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_quick.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_quick_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_quickcontrols2.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_quickparticles_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_quickwidgets.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_scxml.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_scxml_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_sensors.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_sensors_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_serialbus.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_serialbus_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_serialport.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_serialport_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_sql.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_sql_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_svg.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_svg_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_testlib.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_testlib_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_theme_support_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_uiplugin.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_uitools.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_uitools_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_webchannel.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_webchannel_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_webengine.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_webengine_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_webenginecore.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_webenginecore_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_webenginecoreheaders_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_webenginewidgets.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_webenginewidgets_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_websockets.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_websockets_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_webview.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_webview_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_widgets.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_widgets_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_winextras.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_winextras_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_xml.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_xml_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_xmlpatterns.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_zlib_private.pri \
		J:\QT\5.9.9\msvc2017_64\mkspecs\features\qt_functions.prf \
		J:\QT\5.9.9\msvc2017_64\mkspecs\features\qt_config.prf \
		J:\QT\5.9.9\msvc2017_64\mkspecs\win32-msvc\qmake.conf \
		J:\QT\5.9.9\msvc2017_64\mkspecs\features\spec_post.prf \
		.qmake.stash \
		J:\QT\5.9.9\msvc2017_64\mkspecs\features\exclusive_builds.prf \
		J:\QT\5.9.9\msvc2017_64\mkspecs\common\msvc-version.conf \
		J:\QT\5.9.9\msvc2017_64\mkspecs\features\toolchain.prf \
		J:\QT\5.9.9\msvc2017_64\mkspecs\features\default_pre.prf \
		J:\QT\5.9.9\msvc2017_64\mkspecs\features\win32\default_pre.prf \
		J:\QT\5.9.9\msvc2017_64\mkspecs\features\resolve_config.prf \
		J:\QT\5.9.9\msvc2017_64\mkspecs\features\exclusive_builds_post.prf \
		J:\QT\5.9.9\msvc2017_64\mkspecs\features\default_post.prf \
		J:\QT\5.9.9\msvc2017_64\mkspecs\features\precompile_header.prf \
		J:\QT\5.9.9\msvc2017_64\mkspecs\features\warn_on.prf \
		J:\QT\5.9.9\msvc2017_64\mkspecs\features\qt.prf \
		J:\QT\5.9.9\msvc2017_64\mkspecs\features\resources.prf \
		J:\QT\5.9.9\msvc2017_64\mkspecs\features\moc.prf \
		J:\QT\5.9.9\msvc2017_64\mkspecs\features\win32\opengl.prf \
		J:\QT\5.9.9\msvc2017_64\mkspecs\features\uic.prf \
		J:\QT\5.9.9\msvc2017_64\mkspecs\features\qmake_use.prf \
		J:\QT\5.9.9\msvc2017_64\mkspecs\features\file_copies.prf \
		J:\QT\5.9.9\msvc2017_64\mkspecs\features\win32\windows.prf \
		J:\QT\5.9.9\msvc2017_64\mkspecs\features\testcase_targets.prf \
		J:\QT\5.9.9\msvc2017_64\mkspecs\features\exceptions.prf \
		J:\QT\5.9.9\msvc2017_64\mkspecs\features\yacc.prf \
		J:\QT\5.9.9\msvc2017_64\mkspecs\features\lex.prf \
		untitled13.pro \
		J:\QT\5.9.9\msvc2017_64\lib\qtmain.prl \
		J:\QT\5.9.9\msvc2017_64\lib\Qt5Widgets.prl \
		J:\QT\5.9.9\msvc2017_64\lib\Qt5Gui.prl \
		J:\QT\5.9.9\msvc2017_64\lib\Qt5Sql.prl \
		J:\QT\5.9.9\msvc2017_64\lib\Qt5Core.prl
	$(QMAKE) -o Makefile untitled13.pro -spec win32-msvc
J:\QT\5.9.9\msvc2017_64\mkspecs\features\spec_pre.prf:
J:\QT\5.9.9\msvc2017_64\mkspecs\common\angle.conf:
J:\QT\5.9.9\msvc2017_64\mkspecs\common\msvc-desktop.conf:
J:\QT\5.9.9\msvc2017_64\mkspecs\qconfig.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_3danimation.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_3danimation_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_3dcore.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_3dcore_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_3dextras.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_3dextras_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_3dinput.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_3dinput_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_3dlogic.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_3dlogic_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_3dquick.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_3dquick_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_3dquickanimation.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_3dquickanimation_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_3dquickextras.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_3dquickextras_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_3dquickinput.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_3dquickinput_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_3dquickrender.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_3dquickrender_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_3dquickscene2d.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_3dquickscene2d_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_3drender.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_3drender_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_accessibility_support_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_axbase.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_axbase_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_axcontainer.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_axcontainer_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_axserver.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_axserver_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_bluetooth.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_bluetooth_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_bootstrap_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_concurrent.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_concurrent_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_core.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_core_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_dbus.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_dbus_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_designer.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_designer_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_designercomponents_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_egl_support_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_fb_support_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_fontdatabase_support_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_gamepad.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_gamepad_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_gui.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_gui_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_help.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_help_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_location.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_location_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_multimedia.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_multimedia_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_multimediawidgets.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_network.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_network_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_networkauth.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_networkauth_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_nfc.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_nfc_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_opengl.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_opengl_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_openglextensions.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_openglextensions_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_packetprotocol_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_platformcompositor_support_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_positioning.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_positioning_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_printsupport.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_printsupport_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_qml.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_qml_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_qmldebug_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_qmldevtools_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_qmltest.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_qmltest_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_quick.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_quick_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_quickcontrols2.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_quickparticles_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_quickwidgets.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_quickwidgets_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_scxml.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_scxml_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_sensors.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_sensors_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_serialbus.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_serialbus_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_serialport.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_serialport_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_sql.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_sql_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_svg.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_svg_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_testlib.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_testlib_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_theme_support_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_uiplugin.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_uitools.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_uitools_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_webchannel.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_webchannel_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_webengine.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_webengine_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_webenginecore.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_webenginecore_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_webenginecoreheaders_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_webenginewidgets.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_webenginewidgets_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_websockets.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_websockets_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_webview.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_webview_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_widgets.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_widgets_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_winextras.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_winextras_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_xml.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_xml_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_xmlpatterns.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\modules\qt_lib_zlib_private.pri:
J:\QT\5.9.9\msvc2017_64\mkspecs\features\qt_functions.prf:
J:\QT\5.9.9\msvc2017_64\mkspecs\features\qt_config.prf:
J:\QT\5.9.9\msvc2017_64\mkspecs\win32-msvc\qmake.conf:
J:\QT\5.9.9\msvc2017_64\mkspecs\features\spec_post.prf:
.qmake.stash:
J:\QT\5.9.9\msvc2017_64\mkspecs\features\exclusive_builds.prf:
J:\QT\5.9.9\msvc2017_64\mkspecs\common\msvc-version.conf:
J:\QT\5.9.9\msvc2017_64\mkspecs\features\toolchain.prf:
J:\QT\5.9.9\msvc2017_64\mkspecs\features\default_pre.prf:
J:\QT\5.9.9\msvc2017_64\mkspecs\features\win32\default_pre.prf:
J:\QT\5.9.9\msvc2017_64\mkspecs\features\resolve_config.prf:
J:\QT\5.9.9\msvc2017_64\mkspecs\features\exclusive_builds_post.prf:
J:\QT\5.9.9\msvc2017_64\mkspecs\features\default_post.prf:
J:\QT\5.9.9\msvc2017_64\mkspecs\features\precompile_header.prf:
J:\QT\5.9.9\msvc2017_64\mkspecs\features\warn_on.prf:
J:\QT\5.9.9\msvc2017_64\mkspecs\features\qt.prf:
J:\QT\5.9.9\msvc2017_64\mkspecs\features\resources.prf:
J:\QT\5.9.9\msvc2017_64\mkspecs\features\moc.prf:
J:\QT\5.9.9\msvc2017_64\mkspecs\features\win32\opengl.prf:
J:\QT\5.9.9\msvc2017_64\mkspecs\features\uic.prf:
J:\QT\5.9.9\msvc2017_64\mkspecs\features\qmake_use.prf:
J:\QT\5.9.9\msvc2017_64\mkspecs\features\file_copies.prf:
J:\QT\5.9.9\msvc2017_64\mkspecs\features\win32\windows.prf:
J:\QT\5.9.9\msvc2017_64\mkspecs\features\testcase_targets.prf:
J:\QT\5.9.9\msvc2017_64\mkspecs\features\exceptions.prf:
J:\QT\5.9.9\msvc2017_64\mkspecs\features\yacc.prf:
J:\QT\5.9.9\msvc2017_64\mkspecs\features\lex.prf:
untitled13.pro:
J:\QT\5.9.9\msvc2017_64\lib\qtmain.prl:
J:\QT\5.9.9\msvc2017_64\lib\Qt5Widgets.prl:
J:\QT\5.9.9\msvc2017_64\lib\Qt5Gui.prl:
J:\QT\5.9.9\msvc2017_64\lib\Qt5Sql.prl:
J:\QT\5.9.9\msvc2017_64\lib\Qt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile untitled13.pro -spec win32-msvc

qmake_all: FORCE

make_first: release-make_first debug-make_first  FORCE
all: release-all debug-all  FORCE
clean: release-clean debug-clean  FORCE
	-$(DEL_FILE) untitled13.exp
distclean: release-distclean debug-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash untitled13.lib

release-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first

benchmark: first
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
